name: Build .NET MAUI App

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:
    runs-on: macos-latest   # for iOS/Android. Change to ubuntu/windows if only Android/Windows.

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install MAUI workloads
      run: dotnet workload install maui-android maui-ios maui-maccatalyst

    - name: Restore dependencies
      run: dotnet restore

    - name: Build MAUI Android (Release)
      run: dotnet publish -f net8.0-android -c Release -o ./artifacts/android

    # uncomment if you want iOS too
    # - name: Build MAUI iOS (Release)
    #   run: dotnet publish -f net8.0-ios -c Release -o ./artifacts/ios

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Upload Android Artifact
      uses: actions/upload-artifact@v4
      with:
        name: maui-android-apk
        path: ./artifacts/android/**/*.apk
